In [1]:
INPUT = """forward 5
down 7
forward 8
forward 1
forward 1
down 1
down 9
up 4
down 5
down 3
up 1
up 1
forward 1
up 2
forward 5
forward 4
forward 7
down 4
up 9
forward 5
down 5
forward 2
forward 1
forward 3
down 6
up 8
up 8
forward 8
up 7
down 3
down 4
forward 2
down 9
forward 9
down 7
down 9
forward 8
down 5
forward 9
forward 2
forward 7
down 4
forward 8
down 4
up 7
forward 7
forward 7
forward 5
forward 1
down 1
down 5
forward 9
forward 9
down 2
down 2
down 2
forward 4
forward 3
forward 2
down 7
down 7
forward 8
forward 3
forward 1
up 4
forward 9
down 1
up 2
forward 3
forward 7
up 6
up 9
forward 4
down 8
down 5
down 9
forward 9
forward 4
forward 5
forward 3
down 9
forward 1
forward 7
down 5
forward 5
forward 3
down 6
down 5
down 8
forward 6
down 2
forward 2
down 6
forward 1
up 5
up 3
forward 7
down 2
forward 2
forward 1
forward 9
up 9
up 3
forward 5
down 5
forward 9
up 9
down 7
down 1
up 9
down 7
up 4
forward 1
up 2
up 5
down 2
forward 1
down 3
forward 5
down 4
down 1
down 2
down 4
down 5
forward 3
forward 2
forward 6
forward 8
forward 6
down 4
up 7
forward 2
down 3
down 7
down 1
forward 7
forward 1
forward 9
forward 8
forward 3
up 8
forward 4
up 7
up 8
forward 2
forward 5
down 2
down 1
forward 1
up 6
down 7
forward 2
up 6
up 2
forward 5
down 5
forward 5
forward 3
up 7
forward 1
down 3
forward 4
up 5
forward 6
forward 1
up 6
up 7
forward 1
forward 2
up 6
up 6
forward 1
forward 5
up 9
down 4
down 9
down 2
down 5
down 7
down 3
down 2
down 7
forward 8
down 1
forward 6
forward 4
up 8
up 6
forward 5
forward 3
forward 3
down 9
up 1
up 3
up 1
up 8
up 9
down 5
down 5
forward 2
forward 5
down 9
down 1
down 4
forward 5
up 9
forward 2
forward 8
up 1
down 9
down 9
down 2
down 9
up 5
forward 7
down 3
forward 3
down 2
forward 4
forward 9
forward 6
down 1
down 4
down 4
down 7
down 6
down 7
forward 8
forward 1
forward 6
forward 8
up 1
down 2
down 8
forward 4
forward 2
down 1
down 1
down 9
forward 4
down 3
down 5
down 7
down 8
forward 9
forward 9
forward 4
down 9
down 5
up 3
up 2
forward 9
down 6
forward 4
down 9
forward 9
up 6
up 3
forward 3
down 1
up 1
forward 1
forward 8
up 4
up 9
forward 9
down 9
up 4
down 4
up 7
forward 1
down 7
forward 9
down 3
forward 5
forward 4
down 1
down 6
down 5
down 2
forward 7
down 2
forward 1
down 6
forward 8
down 3
down 7
down 1
down 8
up 4
forward 7
forward 9
forward 1
forward 9
forward 8
forward 9
down 4
up 6
down 2
up 8
down 7
down 5
up 2
up 7
down 9
up 1
forward 1
down 9
forward 9
forward 2
forward 1
up 9
down 5
down 1
forward 7
down 5
forward 6
down 3
forward 2
up 4
down 8
down 9
down 9
forward 6
forward 6
down 2
forward 7
up 2
forward 4
down 6
down 4
up 1
up 5
up 2
down 7
down 4
down 4
up 7
forward 8
up 5
down 3
forward 9
forward 8
down 5
forward 2
up 5
down 6
down 8
forward 2
forward 7
up 8
forward 3
up 4
up 8
forward 8
forward 2
forward 8
down 4
down 9
down 1
down 4
down 3
forward 9
forward 5
down 8
forward 7
down 4
up 1
down 4
down 9
forward 4
forward 9
down 8
down 4
down 2
forward 5
forward 2
forward 4
forward 4
forward 5
down 4
up 4
up 9
down 7
forward 2
up 5
forward 3
down 5
down 8
down 8
down 4
forward 9
forward 4
forward 3
down 4
down 4
down 3
up 6
up 2
forward 4
up 8
down 1
forward 2
forward 4
down 7
forward 7
forward 3
down 3
down 1
up 6
up 7
down 9
up 7
forward 9
forward 6
forward 4
down 2
forward 4
forward 4
forward 9
down 5
forward 4
down 9
up 9
up 6
forward 6
down 6
forward 4
down 3
forward 4
down 9
up 1
down 5
down 4
forward 4
down 7
down 3
down 6
down 5
forward 4
forward 3
down 5
forward 6
down 3
up 2
down 2
up 5
down 4
forward 9
forward 1
down 8
forward 8
up 9
down 3
down 4
forward 1
forward 2
up 3
down 9
up 9
forward 3
down 8
forward 7
forward 4
forward 2
up 9
forward 5
forward 7
forward 9
up 4
forward 2
forward 7
down 6
down 2
up 5
forward 3
down 8
up 9
forward 1
forward 9
down 1
up 3
down 5
up 8
down 1
forward 1
forward 8
forward 7
up 9
forward 6
forward 5
forward 9
down 2
forward 4
down 9
forward 1
up 4
forward 2
down 9
down 8
down 5
up 9
forward 6
down 7
up 8
forward 9
up 5
down 3
forward 2
forward 5
forward 6
up 5
forward 6
down 7
down 4
forward 3
down 8
forward 9
down 2
forward 7
down 5
down 2
forward 5
forward 9
forward 3
up 3
up 7
down 4
forward 3
up 8
forward 8
forward 1
down 4
forward 4
forward 2
forward 6
up 1
down 7
forward 3
down 6
down 7
forward 4
forward 5
up 9
forward 3
forward 6
down 2
down 1
forward 5
up 6
down 3
forward 9
down 8
up 3
up 5
up 6
down 7
forward 1
down 8
forward 7
down 3
forward 1
up 9
down 4
up 9
forward 9
down 4
forward 3
up 3
down 1
up 3
up 6
forward 9
forward 6
down 9
down 8
forward 9
up 8
down 8
forward 4
forward 3
forward 2
down 6
down 7
down 1
down 2
down 2
down 5
forward 8
forward 2
down 4
forward 4
down 5
forward 9
forward 1
down 9
up 4
up 5
up 9
forward 5
down 6
up 7
forward 1
up 8
up 3
forward 2
down 1
forward 3
up 8
up 7
down 8
down 9
forward 7
down 2
up 5
up 8
down 3
forward 3
forward 1
up 7
down 3
up 9
down 8
up 5
forward 1
down 8
up 4
up 7
down 2
down 9
forward 3
up 4
forward 4
down 9
forward 1
forward 3
forward 9
up 6
forward 7
up 8
forward 5
down 2
down 2
forward 4
down 6
forward 7
forward 9
up 8
forward 2
up 6
forward 6
forward 1
forward 5
forward 9
forward 5
forward 1
forward 8
forward 4
forward 1
down 2
forward 3
forward 8
forward 6
forward 1
down 7
forward 1
up 2
forward 6
up 2
up 8
down 3
down 9
forward 2
forward 3
up 9
down 7
forward 6
up 3
forward 4
forward 1
up 4
down 1
down 3
down 7
down 4
forward 4
forward 5
up 6
down 4
down 9
down 2
forward 4
down 6
forward 4
forward 5
forward 3
down 9
down 3
up 8
down 2
down 8
up 3
down 1
forward 1
forward 3
down 8
up 3
up 8
up 1
down 3
down 9
down 9
down 6
forward 9
down 7
down 7
down 4
forward 3
forward 3
down 2
down 6
up 9
forward 9
down 9
forward 9
down 8
down 1
up 3
forward 4
up 2
forward 8
up 9
forward 8
up 5
forward 9
down 7
forward 9
forward 7
down 9
down 6
down 5
forward 5
forward 1
forward 8
up 1
up 7
up 5
forward 3
down 1
forward 4
up 6
up 3
down 1
forward 4
down 4
forward 4
forward 5
down 2
down 7
down 1
forward 5
forward 2
forward 5
forward 1
forward 1
down 7
up 7
forward 8
down 7
forward 6
forward 2
down 9
forward 2
down 7
down 5
up 1
down 6
down 7
down 6
down 1
forward 5
down 5
forward 6
up 9
forward 9
up 1
down 9
forward 4
down 6
down 2
forward 3
down 9
up 6
forward 1
down 2
forward 8
forward 7
forward 4
forward 2
forward 7
forward 1
down 9
forward 7
down 4
up 6
down 7
forward 1
up 8
forward 5
up 3
up 1
down 6
forward 9
up 7
up 5
down 2
up 9
up 4
forward 1
forward 1
forward 9
down 3
down 6
forward 1
up 6
up 9
down 9
forward 7
forward 8
up 9
up 4
down 8
up 3
down 8
forward 9
down 3
down 6
forward 7
up 4
forward 7
down 2
down 6
up 4
down 8
down 4
down 2
up 5
down 4
down 2
forward 9
up 9
forward 3
down 9
up 1
down 8
down 5
forward 5
forward 3
up 3
forward 9
down 1
forward 1
up 2
down 9
forward 5
forward 6
up 3
forward 2
forward 8
down 9
up 7
down 8
up 5
forward 9
forward 3
down 7
forward 9
down 8
forward 7
down 6
down 6
down 1
up 4
up 1
forward 3
down 7
up 3
down 3
forward 5
down 8
forward 2
down 9
forward 6
down 6
down 6
forward 9
down 2
forward 6
up 7
down 3
up 5
forward 4
down 7
forward 8
forward 9
forward 7
down 3
forward 7
forward 2
down 6
forward 6
down 2
down 1
forward 4
forward 5
up 6
forward 7
up 3
up 5
forward 2
forward 8
forward 9
down 2
forward 4
forward 5
down 7
up 8
forward 9
forward 9
down 3
down 1
forward 2
forward 2
down 9
up 5
down 5
up 5
down 2
forward 1
down 2
down 9
down 1
forward 2
down 9
down 1
forward 7
down 8
down 5
down 1
up 5
forward 4
down 8
down 6
down 6
forward 9
up 7
up 2
up 8
down 1
forward 9
down 9
down 5
forward 2
down 7
up 8
forward 5
up 2
down 1
down 8
up 5
forward 1
forward 1
down 7
up 2
down 3
up 6
down 6
forward 7
down 3
forward 8
down 1
down 4
down 3
up 8
down 9
up 2
up 5
forward 2
forward 5
forward 8
up 7
forward 4
forward 2
forward 2
forward 3
up 4
down 3
forward 7
forward 9
forward 7"""

In [2]:
with open('input.txt','w') as file:
    file.write(INPUT)

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('input.txt',sep=' ',header=None,names=['dire','value'])
df['value'] = pd.to_numeric(df.value)
df

        dire  value
0    forward      5
1       down      7
2    forward      8
3    forward      1
4    forward      1
..       ...    ...
995       up      4
996     down      3
997  forward      7
998  forward      9
999  forward      7

[1000 rows x 2 columns]

In [5]:
f = df[df['dire']=='forward']['value'].sum()
d = df[df['dire']=='down']['value'].sum()
u = df[df['dire']=='up']['value'].sum()
f*(d-u)

1484118

In [6]:
depth =0
DEPTHS = []

for indx,row in df.iterrows():
    if row['dire'] == 'down':
        depth +=  row['value']
    elif row['dire'] == 'up':
        depth -= row['value']
    DEPTHS.append(depth)

df['depth'] = DEPTHS
df

        dire  value  depth
0    forward      5      0
1       down      7      7
2    forward      8      7
3    forward      1      7
4    forward      1      7
..       ...    ...    ...
995       up      4    735
996     down      3    738
997  forward      7    738
998  forward      9    738
999  forward      7    738

[1000 rows x 3 columns]

In [7]:
df['depth'] = DEPTHS
df

        dire  value  depth
0    forward      5      0
1       down      7      7
2    forward      8      7
3    forward      1      7
4    forward      1      7
..       ...    ...    ...
995       up      4    735
996     down      3    738
997  forward      7    738
998  forward      9    738
999  forward      7    738

[1000 rows x 3 columns]

In [8]:
df['product'] = df['value'] * df['depth']

In [9]:
df

        dire  value  depth  product
0    forward      5      0        0
1       down      7      7       49
2    forward      8      7       56
3    forward      1      7        7
4    forward      1      7        7
..       ...    ...    ...      ...
995       up      4    735     2940
996     down      3    738     2214
997  forward      7    738     5166
998  forward      9    738     6642
999  forward      7    738     5166

[1000 rows x 4 columns]

In [10]:
df[df['dire']=='forward']['value'].cumsum().tail(1) * df[df['dire']=='forward']['product'].cumsum().tail(1)

999    1463827010
dtype: int64